"""Run native MRI + generated PET classification baselines.

All baselines read the AD_Project ``cropped_norm`` MRI volumes directly and
reuse the PET tensors generated by the fixed MRI-to-PET checkpoint. The graph
models use a regular spatial graph built inside the network from pooled native
volumes because AD_Project does not provide the ROI/connectome matrices used by
the original graph papers.

Reference implementations used for the adaptations:
  IBGNN: https://github.com/HennyJie/IBGNN
  SGCN: https://github.com/Houliang-Zhou/SGCN
  ITCFN: https://github.com/justinhxy/ITFC
  MAD-Former: https://github.com/yjy-97/MAD-Former
  3D ResNet: local implementation derived from the standard PyTorch 3D model
"""

from __future__ import annotations

import argparse
import json
import math
import os
import random
import subprocess
import time
from pathlib import Path
from typing import Any

import nibabel as nib
import numpy as np
import pandas as pd
import torch
import torch.nn.functional as F
from sklearn.metrics import (
    accuracy_score,
    balanced_accuracy_score,
    confusion_matrix,
    f1_score,
    matthews_corrcoef,
    precision_score,
    recall_score,
    roc_auc_score,
)
from torch import nn
from torch.utils.data import DataLoader, Dataset

from run_ad_project_binary_repro import DEFAULTS, discover_records


MODEL_SOURCES = {
    "gcn": {
        "name": "vanilla GCN adapted to native spatial nodes",
        "url": "https://github.com/Houliang-Zhou/SGCN/blob/main/kernel/gcn.py",
        "commit": "56c510e26035ea2b44f9190b339d46335a21a15e",
    },
    "resnet": {
        "name": "3D ResNet-18",
        "url": "https://github.com/kenshohara/3D-ResNets-PyTorch",
        "commit": "reference architecture; local implementation in pytorch3dunet/threedresnet.py",
    },
    "resnet50": {
        "name": "3D ResNet-50",
        "url": "https://github.com/kenshohara/3D-ResNets-PyTorch",
        "commit": "reference bottleneck architecture; local 3D implementation",
    },
    "ibgnn": {
        "name": "IBGNN message-passing baseline adapted to spatial nodes",
        "url": "https://github.com/HennyJie/IBGNN",
        "commit": "b50a072538b454fb2850ab75d843027c6873eaa8",
    },
    "sgcn": {
        "name": "sparse interpretable GCN adapted to spatial nodes",
        "url": "https://github.com/Houliang-Zhou/SGCN",
        "commit": "56c510e26035ea2b44f9190b339d46335a21a15e",
    },
    "cnn": {
        "name": "dual-branch 3D CNN",
        "url": "https://github.com/Project-MONAI/tutorials",
        "commit": "standard 3D convolutional baseline",
    },
    "mad_former": {
        "name": "MAD-Former multi-patch attention adaptation",
        "url": "https://github.com/yjy-97/MAD-Former",
        "commit": "4691821046371a8c0f0ff7d7c649cf8cdf6e110d",
    },
    "itcfn": {
        "name": "ITCFN tri-modal co-attention adaptation",
        "url": "https://github.com/justinhxy/ITFC",
        "commit": "839444fe7af1409277f0b182c5a6021db79bf7dc",
    },
}


def set_seed(seed: int) -> None:
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)


def jsonable(value: Any) -> Any:
    if isinstance(value, (np.integer, np.floating)):
        return value.item()
    if isinstance(value, np.ndarray):
        return value.tolist()
    if isinstance(value, Path):
        return str(value)
    if isinstance(value, torch.Tensor):
        return value.detach().cpu().tolist()
    if isinstance(value, dict):
        return {str(k): jsonable(v) for k, v in value.items()}
    if isinstance(value, (list, tuple)):
        return [jsonable(v) for v in value]
    return value


def write_json(path: Path, value: Any) -> None:
    path.write_text(json.dumps(jsonable(value), indent=2, ensure_ascii=True) + "\n")


def safe_metric(function, *args, **kwargs) -> float:
    try:
        return float(function(*args, **kwargs))
    except (ValueError, ZeroDivisionError):
        return float("nan")


def calculate_metrics(labels: np.ndarray, probabilities: np.ndarray, losses: list[float]) -> dict[str, Any]:
    predictions = (probabilities >= 0.5).astype(np.int64)
    metrics = {
        "loss": float(np.mean(losses)) if losses else float("nan"),
        "accuracy": safe_metric(accuracy_score, labels, predictions),
        "balanced_accuracy": safe_metric(balanced_accuracy_score, labels, predictions),
        "recall_macro": safe_metric(recall_score, labels, predictions, average="macro", zero_division=0),
        "precision_macro": safe_metric(precision_score, labels, predictions, average="macro", zero_division=0),
        "f1_macro": safe_metric(f1_score, labels, predictions, average="macro", zero_division=0),
        "mcc": safe_metric(matthews_corrcoef, labels, predictions),
        "auc": safe_metric(roc_auc_score, labels, probabilities),
        "n": int(len(labels)),
        "class_counts": {"0": int((labels == 0).sum()), "1": int((labels == 1).sum())},
        "confusion_matrix": confusion_matrix(labels, predictions, labels=[0, 1]).tolist(),
    }
    # Keep the descriptive fields for backwards compatibility and expose the
    # paper-style aliases used by the result tables.
    metrics.update(
        {
            "ACC": metrics["accuracy"],
            "REC": metrics["recall_macro"],
            "PRE": metrics["precision_macro"],
            "AUC": metrics["auc"],
            "F1": metrics["f1_macro"],
        }
    )
    return metrics


def physical_gpu_index(device: torch.device) -> int:
    visible = os.environ.get("CUDA_VISIBLE_DEVICES", "").strip()
    if visible and visible not in {"NoDevFiles", "-1"}:
        ids = [int(item) for item in visible.split(",") if item.strip().isdigit()]
        return ids[device.index or 0] if ids else device.index or 0
    return device.index or 0


def assert_gpu_idle(device: torch.device, max_memory_mb: int = 128, max_utilization: int = 5) -> None:
    if device.type != "cuda":
        return
    raw = subprocess.check_output(
        ["nvidia-smi", "--query-gpu=index,memory.used,utilization.gpu", "--format=csv,noheader,nounits"],
        text=True,
    )
    status = {}
    for line in raw.splitlines():
        fields = [field.strip() for field in line.split(",")]
        if len(fields) == 3:
            status[int(fields[0])] = (int(fields[1]), int(fields[2]))
    physical = physical_gpu_index(device)
    memory, utilization = status.get(physical, (10**9, 100))
    print(f"GPU check: physical={physical}, memory={memory} MiB, utilization={utilization}%", flush=True)
    if memory > max_memory_mb or utilization > max_utilization:
        raise RuntimeError(f"GPU {physical} is not idle; refusing to start baseline training")


class BinaryFocalLoss(nn.Module):
    """Numerically stable binary focal loss operating on logits."""

    def __init__(self, alpha: float = 0.5, gamma: float = 2.0, reduction: str = "mean") -> None:
        super().__init__()
        if not 0.0 <= alpha <= 1.0:
            raise ValueError("alpha must be in [0, 1]")
        if gamma < 0.0:
            raise ValueError("gamma must be non-negative")
        if reduction not in {"none", "mean", "sum"}:
            raise ValueError("reduction must be one of: none, mean, sum")
        self.alpha = float(alpha)
        self.gamma = float(gamma)
        self.reduction = reduction

    def forward(self, logits: torch.Tensor, targets: torch.Tensor) -> torch.Tensor:
        targets = targets.to(dtype=logits.dtype)
        bce = F.binary_cross_entropy_with_logits(logits, targets, reduction="none")
        p_t = torch.exp(-bce)
        alpha_t = self.alpha * targets + (1.0 - self.alpha) * (1.0 - targets)
        loss = alpha_t * (1.0 - p_t).pow(self.gamma) * bce
        if self.reduction == "sum":
            return loss.sum()
        if self.reduction == "none":
            return loss
        return loss.mean()


def clinical_vector(record: dict[str, Any], category_sizes: tuple[int, ...]) -> np.ndarray:
    pieces: list[np.ndarray] = []
    cate = np.asarray(record["cate_x"], dtype=np.int64).reshape(-1)
    for index, size in enumerate(category_sizes):
        one_hot = np.zeros(int(size), dtype=np.float32)
        if index < len(cate) and 0 <= int(cate[index]) < int(size):
            one_hot[int(cate[index])] = 1.0
        pieces.append(one_hot)
    pieces.append(np.asarray(record["conti_x"], dtype=np.float32).reshape(-1))
    return np.concatenate(pieces).astype(np.float32, copy=False)


class NativeMultimodalDataset(Dataset):
    def __init__(self, records: list[dict[str, Any]], indices: list[int], category_sizes: tuple[int, ...]):
        self.records = records
        self.indices = indices
        self.category_sizes = category_sizes

    def __len__(self) -> int:
        return len(self.indices)

    def __getitem__(self, index: int) -> dict[str, Any]:
        record = self.records[self.indices[index]]
        # AD_Project cropped_norm MRI is intentionally read without transforms.
        image = np.asarray(nib.load(record["image_path"]).dataobj, dtype=np.float32).copy()
        mri = torch.from_numpy(image).unsqueeze(0)
        generated_pet_path = record.get("generated_pet_path")
        if generated_pet_path:
            pet_array = np.asarray(nib.load(generated_pet_path).dataobj, dtype=np.float32).copy()
            if pet_array.ndim == 4 and pet_array.shape[-1] == 1:
                pet_array = pet_array[..., 0]
            if pet_array.ndim != 3:
                raise ValueError(f"Expected a 3D generated PET volume, got {pet_array.shape} for {generated_pet_path}")
            pet = torch.from_numpy(pet_array).unsqueeze(0)
        else:
            pet = torch.load(record["pet_cache_path"], map_location="cpu", weights_only=True).float()
        if tuple(pet.shape) != tuple(mri.shape):
            raise ValueError(f"MRI/PET shape mismatch for {record['name']}: {mri.shape} vs {pet.shape}")
        return {
            "mri": mri,
            "pet": pet,
            "clinical": torch.from_numpy(clinical_vector(record, self.category_sizes)),
            "label": torch.tensor(float(record["label"]), dtype=torch.float32),
            "name": record["name"],
            "subject_id": record["subject_id"],
        }


class ClinicalMLP(nn.Module):
    def __init__(self, input_dim: int, output_dim: int = 64):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(input_dim, output_dim),
            nn.LayerNorm(output_dim),
            nn.GELU(),
            nn.Dropout(0.1),
            nn.Linear(output_dim, output_dim),
            nn.GELU(),
        )

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        return self.net(x)


class CNNEncoder(nn.Module):
    def __init__(self, output_dim: int = 128):
        super().__init__()
        self.pool = nn.AdaptiveAvgPool3d((32, 32, 32))
        self.features = nn.Sequential(
            nn.Conv3d(1, 16, 3, stride=2, padding=1, bias=False),
            nn.BatchNorm3d(16),
            nn.ReLU(inplace=True),
            nn.Conv3d(16, 32, 3, stride=2, padding=1, bias=False),
            nn.BatchNorm3d(32),
            nn.ReLU(inplace=True),
            nn.Conv3d(32, 64, 3, stride=2, padding=1, bias=False),
            nn.BatchNorm3d(64),
            nn.ReLU(inplace=True),
            nn.Conv3d(64, output_dim, 3, stride=2, padding=1, bias=False),
            nn.BatchNorm3d(output_dim),
            nn.ReLU(inplace=True),
        )
        self.avg = nn.AdaptiveAvgPool3d(1)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        return self.avg(self.features(self.pool(x))).flatten(1)


class ResidualBlock3d(nn.Module):
    def __init__(self, in_channels: int, out_channels: int, stride: int):
        super().__init__()
        self.conv1 = nn.Conv3d(in_channels, out_channels, 3, stride=stride, padding=1, bias=False)
        self.bn1 = nn.BatchNorm3d(out_channels)
        self.conv2 = nn.Conv3d(out_channels, out_channels, 3, padding=1, bias=False)
        self.bn2 = nn.BatchNorm3d(out_channels)
        self.skip = (
            nn.Sequential(
                nn.Conv3d(in_channels, out_channels, 1, stride=stride, bias=False),
                nn.BatchNorm3d(out_channels),
            )
            if in_channels != out_channels or stride != 1
            else nn.Identity()
        )

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        residual = self.skip(x)
        x = F.relu(self.bn1(self.conv1(x)), inplace=True)
        x = self.bn2(self.conv2(x))
        return F.relu(x + residual, inplace=True)


class ResNetEncoder(nn.Module):
    def __init__(self, output_dim: int = 128):
        super().__init__()
        self.pool = nn.AdaptiveAvgPool3d((32, 32, 32))
        self.stem = nn.Sequential(
            nn.Conv3d(1, 16, 3, stride=1, padding=1, bias=False),
            nn.BatchNorm3d(16),
            nn.ReLU(inplace=True),
        )
        self.layers = nn.Sequential(
            ResidualBlock3d(16, 16, 1),
            ResidualBlock3d(16, 32, 2),
            ResidualBlock3d(32, 32, 1),
            ResidualBlock3d(32, 64, 2),
            ResidualBlock3d(64, 64, 1),
            ResidualBlock3d(64, 128, 2),
            ResidualBlock3d(128, 128, 1),
        )
        self.avg = nn.AdaptiveAvgPool3d(1)
        self.proj = nn.Linear(128, output_dim)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        x = self.pool(x)
        x = self.layers(self.stem(x))
        return self.proj(self.avg(x).flatten(1))


class BottleneckBlock3d(nn.Module):
    expansion = 4

    def __init__(self, in_channels: int, planes: int, stride: int):
        super().__init__()
        out_channels = planes * self.expansion
        self.conv1 = nn.Conv3d(in_channels, planes, 1, bias=False)
        self.bn1 = nn.BatchNorm3d(planes)
        self.conv2 = nn.Conv3d(planes, planes, 3, stride=stride, padding=1, bias=False)
        self.bn2 = nn.BatchNorm3d(planes)
        self.conv3 = nn.Conv3d(planes, out_channels, 1, bias=False)
        self.bn3 = nn.BatchNorm3d(out_channels)
        self.skip = (
            nn.Sequential(
                nn.Conv3d(in_channels, out_channels, 1, stride=stride, bias=False),
                nn.BatchNorm3d(out_channels),
            )
            if in_channels != out_channels or stride != 1
            else nn.Identity()
        )

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        residual = self.skip(x)
        x = F.relu(self.bn1(self.conv1(x)), inplace=True)
        x = F.relu(self.bn2(self.conv2(x)), inplace=True)
        x = self.bn3(self.conv3(x))
        return F.relu(x + residual, inplace=True)


class ResNet50Encoder(nn.Module):
    """Compact 3D ResNet-50 encoder with [3, 4, 6, 3] bottleneck blocks."""

    def __init__(self, output_dim: int = 128):
        super().__init__()
        self.pool = nn.AdaptiveAvgPool3d((32, 32, 32))
        self.stem = nn.Sequential(
            nn.Conv3d(1, 16, 3, stride=1, padding=1, bias=False),
            nn.BatchNorm3d(16),
            nn.ReLU(inplace=True),
        )
        self.layer1 = self._make_layer(16, 16, 3, 1)
        self.layer2 = self._make_layer(64, 32, 4, 2)
        self.layer3 = self._make_layer(128, 64, 6, 2)
        self.layer4 = self._make_layer(256, 128, 3, 2)
        self.avg = nn.AdaptiveAvgPool3d(1)
        self.proj = nn.Linear(512, output_dim)

    @staticmethod
    def _make_layer(in_channels: int, planes: int, blocks: int, stride: int) -> nn.Sequential:
        layers = [BottleneckBlock3d(in_channels, planes, stride)]
        channels = planes * BottleneckBlock3d.expansion
        layers.extend(BottleneckBlock3d(channels, planes, 1) for _ in range(blocks - 1))
        return nn.Sequential(*layers)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        x = self.pool(x)
        x = self.stem(x)
        x = self.layer1(x)
        x = self.layer2(x)
        x = self.layer3(x)
        x = self.layer4(x)
        return self.proj(self.avg(x).flatten(1))


class ImageClinicalClassifier(nn.Module):
    def __init__(self, encoder_factory, clinical_dim: int, feature_dim: int = 128):
        super().__init__()
        self.mri_encoder = encoder_factory(feature_dim)
        self.pet_encoder = encoder_factory(feature_dim)
        self.clinical = ClinicalMLP(clinical_dim, feature_dim)
        self.head = nn.Sequential(
            nn.Linear(feature_dim * 3, feature_dim),
            nn.LayerNorm(feature_dim),
            nn.GELU(),
            nn.Dropout(0.2),
            nn.Linear(feature_dim, 1),
        )

    def forward(self, mri: torch.Tensor, pet: torch.Tensor, clinical: torch.Tensor) -> torch.Tensor:
        features = [self.mri_encoder(mri), self.pet_encoder(pet), self.clinical(clinical)]
        return self.head(torch.cat(features, dim=1)).squeeze(1)


def grid_edges(grid: tuple[int, int, int]) -> tuple[torch.Tensor, torch.Tensor]:
    d, h, w = grid
    edges: list[tuple[int, int]] = []
    for z in range(d):
        for y in range(h):
            for x in range(w):
                node = (z * h + y) * w + x
                edges.append((node, node))
                for dz, dy, dx in ((1, 0, 0), (0, 1, 0), (0, 0, 1)):
                    nz, ny, nx = z + dz, y + dy, x + dx
                    if nz < d and ny < h and nx < w:
                        other = (nz * h + ny) * w + nx
                        edges.extend(((node, other), (other, node)))
    edge_index = torch.tensor(edges, dtype=torch.long).t().contiguous()
    edge_weight = torch.ones(edge_index.shape[1], dtype=torch.float32)
    return edge_index, edge_weight


class SpatialGraphEncoder(nn.Module):
    def __init__(self, grid: tuple[int, int, int] = (4, 5, 4)):
        super().__init__()
        edge_index, edge_weight = grid_edges(grid)
        self.grid = grid
        self.nodes = int(np.prod(grid))
        self.pool = nn.AdaptiveAvgPool3d(grid)
        self.register_buffer("edge_index", edge_index, persistent=False)
        self.register_buffer("base_edge_weight", edge_weight, persistent=False)
        self.register_buffer("base_adjacency", self._make_adjacency(edge_index, edge_weight), persistent=False)

    def _make_adjacency(self, edge_index: torch.Tensor, edge_weight: torch.Tensor) -> torch.Tensor:
        adjacency = torch.zeros(self.nodes, self.nodes)
        adjacency[edge_index[0], edge_index[1]] = edge_weight
        degree = adjacency.sum(dim=1).clamp_min(1.0)
        scale = degree.rsqrt()
        return scale[:, None] * adjacency * scale[None, :]

    def nodes_from_images(self, mri: torch.Tensor, pet: torch.Tensor) -> torch.Tensor:
        mri_nodes = self.pool(mri).flatten(2).transpose(1, 2)
        pet_nodes = self.pool(pet).flatten(2).transpose(1, 2)
        return torch.cat([mri_nodes, pet_nodes], dim=-1)


class DenseGraphConv(nn.Module):
    def __init__(self, in_dim: int, out_dim: int):
        super().__init__()
        self.linear = nn.Linear(in_dim, out_dim)

    def forward(self, x: torch.Tensor, adjacency: torch.Tensor) -> torch.Tensor:
        return torch.bmm(adjacency, self.linear(x))


class GCNClassifier(nn.Module):
    def __init__(self, clinical_dim: int):
        super().__init__()
        self.graph = SpatialGraphEncoder()
        self.conv1 = DenseGraphConv(2, 64)
        self.conv2 = DenseGraphConv(64, 64)
        self.clinical = ClinicalMLP(clinical_dim, 64)
        self.head = nn.Sequential(nn.Linear(192, 96), nn.ReLU(inplace=True), nn.Dropout(0.2), nn.Linear(96, 1))

    def forward(self, mri, pet, clinical):
        x = self.graph.nodes_from_images(mri, pet)
        adjacency = self.graph.base_adjacency.expand(x.shape[0], -1, -1)
        x = F.relu(self.conv1(x, adjacency), inplace=True)
        x = F.relu(self.conv2(x, adjacency), inplace=True)
        graph = torch.cat([x.mean(dim=1), x.amax(dim=1)], dim=1)
        return self.head(torch.cat([graph, self.clinical(clinical)], dim=1)).squeeze(1)


class SGCNClassifier(nn.Module):
    def __init__(self, clinical_dim: int):
        super().__init__()
        self.graph = SpatialGraphEncoder()
        self.node_logits = nn.Parameter(torch.zeros(self.graph.nodes, 2))
        self.edge_gate = nn.Sequential(nn.Linear(4, 32), nn.ReLU(inplace=True), nn.Linear(32, 1))
        self.conv1 = DenseGraphConv(2, 64)
        self.conv2 = DenseGraphConv(64, 64)
        self.clinical = ClinicalMLP(clinical_dim, 64)
        self.head = nn.Sequential(nn.Linear(192, 96), nn.ReLU(inplace=True), nn.Dropout(0.2), nn.Linear(96, 1))
        self.last_node_probability = None
        self.last_edge_probability = None

    def _adaptive_adjacency(self, x: torch.Tensor) -> tuple[torch.Tensor, torch.Tensor, torch.Tensor]:
        node_probability = torch.sigmoid(self.node_logits)
        masked = x * node_probability.unsqueeze(0)
        src, dst = self.graph.edge_index
        pair = torch.cat([masked[:, src], masked[:, dst]], dim=-1)
        edge_probability = torch.sigmoid(self.edge_gate(pair).squeeze(-1))
        adjacency = torch.zeros(x.shape[0], self.graph.nodes, self.graph.nodes, device=x.device, dtype=x.dtype)
        adjacency[:, src, dst] = edge_probability.to(dtype=adjacency.dtype).unsqueeze(0)
        degree = adjacency.sum(dim=-1).clamp_min(1.0)
        scale = degree.rsqrt()
        adjacency = scale.unsqueeze(-1) * adjacency * scale.unsqueeze(-2)
        return masked, adjacency, node_probability, edge_probability

    def regularization_loss(self) -> torch.Tensor:
        node_probability = torch.sigmoid(self.node_logits)
        node_entropy = -(node_probability * torch.log(node_probability + 1e-6) + (1 - node_probability) * torch.log(1 - node_probability + 1e-6)).mean()
        edge_probability = self.last_edge_probability
        if edge_probability is None:
            return node_entropy * 0.0
        edge_entropy = -(edge_probability * torch.log(edge_probability + 1e-6) + (1 - edge_probability) * torch.log(1 - edge_probability + 1e-6)).mean()
        return 1e-4 * (node_probability.mean() + edge_probability.mean()) + 1e-4 * (node_entropy + edge_entropy)

    def forward(self, mri, pet, clinical):
        x = self.graph.nodes_from_images(mri, pet)
        x, adjacency, node_probability, edge_probability = self._adaptive_adjacency(x)
        self.last_node_probability = node_probability
        self.last_edge_probability = edge_probability
        x = F.relu(self.conv1(x, adjacency), inplace=True)
        x = F.relu(self.conv2(x, adjacency), inplace=True)
        graph = torch.cat([x.mean(dim=1), x.amax(dim=1)], dim=1)
        return self.head(torch.cat([graph, self.clinical(clinical)], dim=1)).squeeze(1)


class IBGMessageConv(nn.Module):
    def __init__(self, in_dim: int, out_dim: int):
        super().__init__()
        self.node_linear = nn.Linear(in_dim, out_dim)
        self.message = nn.Sequential(
            nn.Linear(out_dim * 2 + 1, out_dim),
            nn.ReLU(inplace=True),
            nn.Linear(out_dim, out_dim),
        )

    def forward(self, x: torch.Tensor, edge_index: torch.Tensor, edge_weight: torch.Tensor) -> torch.Tensor:
        z = self.node_linear(x)
        edge_weight = edge_weight.to(device=z.device, dtype=z.dtype)
        src, dst = edge_index
        weights = edge_weight.view(1, -1, 1).expand(z.shape[0], -1, -1)
        messages = self.message(torch.cat([z[:, src], z[:, dst], weights], dim=-1))
        out = torch.zeros_like(z)
        out.index_add_(1, dst, messages)
        degree = torch.zeros(z.shape[1], device=z.device, dtype=z.dtype)
        degree.index_add_(0, dst, edge_weight)
        return out / degree.clamp_min(1.0).view(1, -1, 1)


class IBGNNClassifier(nn.Module):
    def __init__(self, clinical_dim: int):
        super().__init__()
        self.graph = SpatialGraphEncoder()
        self.conv1 = IBGMessageConv(2, 64)
        self.conv2 = IBGMessageConv(64, 64)
        self.conv3 = IBGMessageConv(64, 64)
        self.clinical = ClinicalMLP(clinical_dim, 64)
        self.head = nn.Sequential(nn.Linear(128, 96), nn.ReLU(inplace=True), nn.Dropout(0.2), nn.Linear(96, 1))

    def forward(self, mri, pet, clinical):
        x = self.graph.nodes_from_images(mri, pet)
        edge_index = self.graph.edge_index
        edge_weight = self.graph.base_edge_weight.to(x.device)
        x = F.relu(self.conv1(x, edge_index, edge_weight), inplace=True)
        x = F.dropout(x, p=0.1, training=self.training)
        x = F.relu(self.conv2(x, edge_index, edge_weight), inplace=True)
        x = F.relu(self.conv3(x, edge_index, edge_weight), inplace=True)
        graph = x.mean(dim=1)
        return self.head(torch.cat([graph, self.clinical(clinical)], dim=1)).squeeze(1)


class PatchTransformer(nn.Module):
    def __init__(self, patch_size: int, dim: int = 64):
        super().__init__()
        self.patch = nn.Conv3d(1, dim, kernel_size=patch_size, stride=patch_size)
        token_count = (32 // patch_size) ** 3
        self.cls = nn.Parameter(torch.zeros(1, 1, dim))
        self.position = nn.Parameter(torch.zeros(1, token_count + 1, dim))
        layer = nn.TransformerEncoderLayer(d_model=dim, nhead=4, dim_feedforward=dim * 4, dropout=0.1, batch_first=True, norm_first=True)
        self.encoder = nn.TransformerEncoder(layer, num_layers=2)
        nn.init.normal_(self.position, std=0.02)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        x = F.adaptive_avg_pool3d(x, (32, 32, 32))
        tokens = self.patch(x).flatten(2).transpose(1, 2)
        cls = self.cls.expand(tokens.shape[0], -1, -1)
        tokens = torch.cat([cls, tokens], dim=1) + self.position
        return self.encoder(tokens)[:, 0]


class MADFormerClassifier(nn.Module):
    def __init__(self, clinical_dim: int):
        super().__init__()
        self.mri_patch8 = PatchTransformer(8)
        self.mri_patch4 = PatchTransformer(4)
        self.pet_patch8 = PatchTransformer(8)
        self.pet_patch4 = PatchTransformer(4)
        self.clinical = ClinicalMLP(clinical_dim, 64)
        self.head = nn.Sequential(nn.Linear(320, 128), nn.LayerNorm(128), nn.GELU(), nn.Dropout(0.2), nn.Linear(128, 1))

    def forward(self, mri, pet, clinical):
        features = [self.mri_patch8(mri), self.mri_patch4(mri), self.pet_patch8(pet), self.pet_patch4(pet), self.clinical(clinical)]
        return self.head(torch.cat(features, dim=1)).squeeze(1)


class ITCFNClassifier(nn.Module):
    def __init__(self, clinical_dim: int):
        super().__init__()
        self.mri_encoder = CNNEncoder(128)
        self.pet_encoder = CNNEncoder(128)
        self.clinical = ClinicalMLP(clinical_dim, 128)
        self.cross_attention = nn.MultiheadAttention(128, 4, dropout=0.1, batch_first=True)
        self.norm = nn.LayerNorm(128)
        self.head = nn.Sequential(nn.Linear(384, 128), nn.GELU(), nn.Dropout(0.2), nn.Linear(128, 1))

    def forward(self, mri, pet, clinical):
        tokens = torch.stack([self.mri_encoder(mri), self.pet_encoder(pet), self.clinical(clinical)], dim=1)
        outputs = []
        for index in range(3):
            query = tokens[:, index:index + 1]
            context = torch.cat([tokens[:, :index], tokens[:, index + 1:]], dim=1)
            attended, _ = self.cross_attention(query, context, context)
            outputs.append(self.norm(query + attended).squeeze(1))
        return self.head(torch.cat(outputs, dim=1)).squeeze(1)


def build_model(name: str, clinical_dim: int) -> nn.Module:
    if name == "cnn":
        return ImageClinicalClassifier(CNNEncoder, clinical_dim)
    if name == "resnet":
        return ImageClinicalClassifier(ResNetEncoder, clinical_dim)
    if name == "resnet50":
        return ImageClinicalClassifier(ResNet50Encoder, clinical_dim)
    if name == "gcn":
        return GCNClassifier(clinical_dim)
    if name == "sgcn":
        return SGCNClassifier(clinical_dim)
    if name == "ibgnn":
        return IBGNNClassifier(clinical_dim)
    if name == "mad_former":
        return MADFormerClassifier(clinical_dim)
    if name == "itcfn":
        return ITCFNClassifier(clinical_dim)
    raise ValueError(f"Unknown model: {name}")


def move_batch(batch: dict[str, Any], device: torch.device) -> tuple[torch.Tensor, ...]:
    return tuple(batch[key].to(device, non_blocking=True) for key in ("mri", "pet", "clinical", "label"))


@torch.no_grad()
def evaluate(model: nn.Module, loader: DataLoader, device: torch.device, amp: bool, criterion: nn.Module, prediction_path: Path | None = None) -> dict[str, Any]:
    model.eval()
    labels: list[np.ndarray] = []
    probabilities: list[np.ndarray] = []
    losses: list[float] = []
    rows: list[dict[str, Any]] = []
    enabled = amp and device.type == "cuda"
    for batch in loader:
        mri, pet, clinical, target = move_batch(batch, device)
        with torch.autocast(device_type="cuda", dtype=torch.float16, enabled=enabled):
            logits = model(mri, pet, clinical)
            loss = criterion(logits, target)
        probs = torch.sigmoid(logits).float().cpu().numpy()
        y = target.long().cpu().numpy()
        labels.append(y)
        probabilities.append(probs)
        losses.append(float(loss.detach().cpu()))
        for name, subject, label, probability in zip(batch["name"], batch["subject_id"], y, probs):
            rows.append({"name": name, "subject_id": subject, "label": int(label), "probability": float(probability), "prediction": int(probability >= 0.5)})
    y = np.concatenate(labels) if labels else np.empty(0, dtype=np.int64)
    p = np.concatenate(probabilities) if probabilities else np.empty(0, dtype=np.float32)
    metrics = calculate_metrics(y, p, losses)
    if prediction_path is not None:
        pd.DataFrame(rows).to_csv(prediction_path, index=False)
    return metrics


def load_records(
    dataset: str, reference_run: Path, category_sizes: tuple[int, ...], generated_pet_root: Path | None = None
) -> tuple[list[dict[str, Any]], dict[str, list[int]], dict[str, Any]]:
    default = DEFAULTS[dataset]
    records, metadata = discover_records(
        dataset, Path(default["data_root"]), Path(default["table_path"]),
        generated_pet_root=Path(generated_pet_root) if generated_pet_root else None,
    )
    manifest = pd.read_csv(reference_run / "manifest.csv")
    run_config = json.loads((reference_run / "run_config.json").read_text())
    record_by_name = {record["name"]: record for record in records}
    ordered: list[dict[str, Any]] = []
    split_indices = {"train": [], "val": [], "test": []}
    for _, row in manifest.sort_values("index").iterrows():
        name = str(row["name"])
        if name not in record_by_name:
            raise RuntimeError(f"Reference manifest record disappeared: {name}")
        record = record_by_name[name]
        generated_pet_path = row.get("generated_pet_path")
        if pd.notna(generated_pet_path) and str(generated_pet_path).strip():
            record["generated_pet_path"] = str(generated_pet_path)
        else:
            cache_dir = run_config.get("mri_to_pet_cache_dir")
            if not cache_dir:
                raise ValueError(
                    "Reference manifest has no generated_pet_path and reference run has no mri_to_pet_cache_dir"
                )
            record["pet_cache_path"] = str(Path(cache_dir) / f"{int(row['index']):05d}.pt")
        ordered.append(record)
        split_indices[str(row["split"])].append(len(ordered) - 1)
    if len(ordered) != len(manifest):
        raise RuntimeError("Reference manifest and discovered records have different sizes")
    return ordered, split_indices, {"data": metadata, "run_config": run_config, "category_sizes": category_sizes}


def train_one(args: argparse.Namespace) -> None:
    dataset = args.dataset
    model_name = args.model
    reference_run = Path(args.reference_run or f"runs/{dataset}_binary_mri2pet_retrained_native")
    output_dir = Path(args.output_dir or f"runs/baseline_comparison/{dataset}/{model_name}")
    output_dir.mkdir(parents=True, exist_ok=True)
    if args.num_threads > 0:
        torch.set_num_threads(args.num_threads)
        torch.set_num_interop_threads(1)
    set_seed(args.seed)
    device = torch.device(args.device)
    if device.type == "cuda":
        if not torch.cuda.is_available():
            raise RuntimeError("CUDA requested but unavailable")
        assert_gpu_idle(device)
        torch.cuda.set_device(device.index if device.index is not None else 0)
    torch.set_float32_matmul_precision("high")

    default = DEFAULTS[dataset]
    discovered, discovery_metadata = discover_records(
        dataset,
        Path(default["data_root"]),
        Path(default["table_path"]),
    )
    category_sizes = tuple(discovery_metadata["category_sizes"])
    records, splits, loaded_metadata = load_records(
        dataset, reference_run, category_sizes, generated_pet_root=args.generated_pet_root
    )
    if not all(
        (Path(record["generated_pet_path"]).is_file() if record.get("generated_pet_path") else Path(record["pet_cache_path"]).is_file())
        for record in records
    ):
        raise FileNotFoundError("The requested MRI-to-PET inputs are incomplete")
    data_metadata = loaded_metadata["data"]
    clinical_dim = int(sum(data_metadata["category_sizes"]) + data_metadata["num_continuous"])
    loaders = {
        split: DataLoader(
            NativeMultimodalDataset(records, indices, category_sizes),
            batch_size=args.batch_size,
            shuffle=split == "train",
            num_workers=args.workers,
            pin_memory=device.type == "cuda",
            drop_last=False,
        )
        for split, indices in splits.items()
    }
    model = build_model(model_name, clinical_dim).to(device)
    optimizer = torch.optim.Adam(model.parameters(), lr=args.lr, weight_decay=args.weight_decay)
    criterion = (
        BinaryFocalLoss(alpha=args.alpha, gamma=args.gamma)
        if args.focal_loss
        else nn.BCEWithLogitsLoss()
    )
    scaler = torch.amp.GradScaler("cuda", enabled=args.amp and device.type == "cuda")
    amp_enabled = args.amp and device.type == "cuda"
    run_config = {
        "dataset": dataset,
        "model": model_name,
        "model_source": MODEL_SOURCES[model_name],
        "reference_run": reference_run,
        "mri_to_pet_checkpoint": loaded_metadata["run_config"]["reference_mri_to_pet_checkpoint"],
        "mri_to_pet_cache_dir": loaded_metadata["run_config"].get("mri_to_pet_cache_dir"),
        "data_root": default["data_root"],
        "table_path": default["table_path"],
        "native_mri_policy": "direct_cropped_norm_read_no_runtime_transform",
        "image_conditions": ["cropped_norm_mri", "generated_pet"],
        "clinical_features": "one_hot_categorical_plus_train_table_zscore_numeric",
        "spatial_graph": [4, 5, 4] if model_name in {"gcn", "sgcn", "ibgnn"} else None,
        "seed": args.seed,
        "epochs": args.epochs,
        "early_stopping_patience": args.early_stopping_patience,
        "model_selection_metric": "validation_auc_with_balanced_accuracy_fallback",
        "num_threads": args.num_threads,
        "batch_size": args.batch_size,
        "lr": args.lr,
        "weight_decay": args.weight_decay,
        "amp": args.amp,
        "device": str(device),
        "splits": {key: len(value) for key, value in splits.items()},
        "clinical_dim": clinical_dim,
        "clinical_columns": data_metadata.get("numeric_columns", []) + data_metadata.get("categorical_columns", []),
        "excluded_columns": data_metadata.get("excluded_columns", []),
        "focal_loss": {"enabled": args.focal_loss, "alpha": args.alpha, "gamma": args.gamma},
    }
    write_json(output_dir / "run_config.json", run_config)
    write_json(output_dir / "model_sources.json", MODEL_SOURCES)
    manifest_rows = []
    for i, record in enumerate(records):
        row = {
            "index": i,
            "split": next(split for split, indices in splits.items() if i in indices),
            "name": record["name"],
            "subject_id": record["subject_id"],
            "label": record["label"],
            "mri_path": record["image_path"],
            "pet_cache_path": record.get("pet_cache_path"),
            "generated_pet_path": record.get("generated_pet_path"),
        }
        manifest_rows.append(row)
    pd.DataFrame(manifest_rows).to_csv(output_dir / "manifest.csv", index=False)
    print(f"{dataset}/{model_name}: samples={len(records)} splits={run_config['splits']} clinical_dim={clinical_dim}", flush=True)

    best_auc = -float("inf")
    best_epoch = -1
    epochs_without_improvement = 0
    history: list[dict[str, Any]] = []
    start = time.time()
    for epoch in range(1, args.epochs + 1):
        model.train()
        losses: list[float] = []
        for batch in loaders["train"]:
            mri, pet, clinical, target = move_batch(batch, device)
            optimizer.zero_grad(set_to_none=True)
            with torch.autocast(device_type="cuda", dtype=torch.float16, enabled=amp_enabled):
                logits = model(mri, pet, clinical)
                loss = criterion(logits, target)
                if isinstance(model, SGCNClassifier):
                    loss = loss + model.regularization_loss()
            if scaler.is_enabled():
                scaler.scale(loss).backward()
                scaler.unscale_(optimizer)
                torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
                scaler.step(optimizer)
                scaler.update()
            else:
                loss.backward()
                torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
                optimizer.step()
            losses.append(float(loss.detach().cpu()))
        val = evaluate(model, loaders["val"], device, args.amp, criterion)
        row = {"epoch": epoch, "train_loss": float(np.mean(losses)), "val": val, "elapsed_seconds": time.time() - start}
        history.append(row)
        with (output_dir / "history.jsonl").open("a", encoding="utf-8") as handle:
            handle.write(json.dumps(jsonable(row)) + "\n")
        score = val["auc"] if np.isfinite(val["auc"]) else val["balanced_accuracy"]
        if score > best_auc:
            best_auc = score
            best_epoch = epoch
            epochs_without_improvement = 0
            torch.save({"model_state": model.state_dict(), "epoch": epoch, "metrics": val, "run_config": jsonable(run_config)}, output_dir / "best.pt")
        else:
            epochs_without_improvement += 1
        torch.save({"model_state": model.state_dict(), "epoch": epoch, "metrics": val, "run_config": jsonable(run_config)}, output_dir / "last.pt")
        print(
            f"epoch={epoch:02d}/{args.epochs} train_loss={row['train_loss']:.5f} "
            f"val_auc={val['auc']:.4f} val_acc={val['accuracy']:.4f} "
            f"no_improve={epochs_without_improvement}/{args.early_stopping_patience} "
            f"({row['elapsed_seconds']:.1f}s)",
            flush=True,
        )
        if (
            args.early_stopping_patience > 0
            and epochs_without_improvement >= args.early_stopping_patience
        ):
            print(
                f"early stopping at epoch {epoch}: validation score did not improve "
                f"for {args.early_stopping_patience} epochs",
                flush=True,
            )
            break

    best = torch.load(output_dir / "best.pt", map_location=device, weights_only=False)
    model.load_state_dict(best["model_state"])
    test = evaluate(model, loaders["test"], device, args.amp, criterion, output_dir / "test_predictions.csv")
    result = {"model": model_name, "dataset": dataset, "best_epoch": best_epoch, "best_validation": best["metrics"], "test": test, "history": history, "gpu_visible_devices": os.environ.get("CUDA_VISIBLE_DEVICES")}
    write_json(output_dir / "metrics.json", result)
    print("test:", json.dumps(jsonable(test), ensure_ascii=True), flush=True)


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--dataset", choices=sorted(DEFAULTS), required=True)
    parser.add_argument("--model", choices=sorted(MODEL_SOURCES), required=True)
    parser.add_argument("--reference-run")
    parser.add_argument("--generated-pet-root")
    parser.add_argument("--output-dir")
    parser.add_argument("--device", default="cuda")
    parser.add_argument("--seed", type=int, default=2026)
    parser.add_argument("--alpha", type=float, default=0.5)
    parser.add_argument("--gamma", type=float, default=0.0)
    parser.add_argument("--focal-loss", action=argparse.BooleanOptionalAction, default=False)
    parser.add_argument("--epochs", type=int, default=100)
    parser.add_argument("--early-stopping-patience", type=int, default=15)
    parser.add_argument("--batch-size", type=int, default=2)
    parser.add_argument("--workers", type=int, default=0)
    parser.add_argument("--num-threads", type=int, default=4)
    parser.add_argument("--lr", type=float, default=6e-5)
    parser.add_argument("--weight-decay", type=float, default=0.0)
    parser.add_argument("--amp", action=argparse.BooleanOptionalAction, default=True)
    return parser


if __name__ == "__main__":
    train_one(build_parser().parse_args())
